### PR TITLE
Ts table card

### PR DESCRIPTION
**Pull request by gustavo-salazar**
Migration to typescript and visual framework for the `Table/View/Grid` and subcomponents.

Component Migrated:
* `Table/Card`
* `Table/View/Grid`

Extracted component:
* `pages/Set` =>`components/Set/List/AllSetDownload`
* `pages/Set` =>`components/Set/List`

For testing purposes, I migrated the `pages/Set` as well. So the Browse by Set on Grid and Table views is now on TS!

Other changes:
* `React.memo` removed from Table, not sure it was really doing anything, and generic types were getting obscured by it. Besides, there is a chance that the upcoming React 19, will take carte of all the memoizations.

**Note 1:** Fifth of a series of PRs chained to migrate `<Table>` and all its subcomponents. Make sure to review #629  first. And, when merging, delete the branch to update the next PRs.

### CODE REVIEW

**Review by tgrego — CHANGES_REQUESTED** [review]
There's a bug on the Browse by Set on Grid view.
The matching entries for sets there are N/A, it does not get the entries but an [object Object].
Everything else looks good to me.

**Review by matthiasblum — CHANGES_REQUESTED** [review]
I can reproduce the bug spotted by @tgrego.
I looks like the data used to populate the cards is now taken from `/api//set/all/entry/` while expecting the payload from `/api/set/all/entry/pfam/?page_size=20&extra_fields=counters,description`.

Out of scope of the PR, but since each card has a padding of `1em`, the footer should be changed from

https://github.com/ProteinsWebTeam/interpro7-client/blob/75e9303209edab048fe789506f10c2e83e337e69/src/components/SimpleCommonComponents/Card/styles.css#L68

to

```css
    padding: 0.7rem 0 0;
```

**Comment by gustavo-salazar** [comment]
> I looks like the data used to populate the cards is now taken from `/api//set/all/entry/` while expecting the payload from `/api/set/all/entry/pfam/?page_size=20&extra_fields=counters,description`.

From what I can see it's getting the data from the right place, it was an issue only with the structure of it. It was expecting `{entries: 5}`, but now is `{entries: {total: 5}}`

**Review by tgrego — APPROVED** [review]
That did it, all seems good now!

**Review by matthiasblum — APPROVED** [review]
All good!

**Pull request merged**
