### PR TITLE
Description failover

### LINKED ISSUE #465: Show InterPro description when empty Pfam description
About 1700 Pfam don't have a description. Alex suggested that for those cases we could display the InterPro description instead (when the signature is integrated).
Some examples below:
PF00010
PF00017
PF00019
PF00020
PF00022
PF00028
PF00032
PF00033
PF00038
PF00039

### PR DESCRIPTION
**Pull request by gustavo-salazar**
If an entry doesn't have a description, it tries to display the description of its integrated InterPro entry.

FIX #465

### CODE REVIEW

**Review by typhainepl — COMMENTED** [review]
I don't have any comment on the code itself, it seems pretty straight forward.
A few improvement suggestions:

- Can you change `From IPR...` to `Imported from IPR...`?
- The content of the tooltip could be changed to `The member database didn't provide a description for this signature. The description displayed has been imported from IPR..., the InterPro entry in which the signature is integrated.`

Not related to the description, but to the table shown above, would it be possible to have the second column closer to the first one? It looks very far away for no reason.

**Comment by typhainepl** [comment]
The description part looks good to me.

**Comment by gustavo-salazar** [comment]
> The description part looks good to me. One last little change to be made in the table: can you left-align the text of the first column?

Changes are done. Plus I disabled the overlay for runtime errors.

**Comment by typhainepl** [comment]
Looks good to me. Good job :)

**Review by typhainepl — APPROVED** [review]

**Review by laisecf — APPROVED** [review]

**Pull request merged**
