### PR TITLE
Release 98

### PR DESCRIPTION
**Pull request by gustavo-salazar**
All the changes that were already reviewed in:
* #547
* #548 
* #549 
* #550
* #551 
* #553  
* #554
* #557 
* #558
* #559 
* #560 
* #561 
* #562 

**Note 1:** Requires to be installed with npm7+ and node 18+
**Note 2:** Some features require the latest API changes in [this PR](https://github.com/ProteinsWebTeam/interpro7-api/pull/124)
**Note 3:** Currently deployed in the [future](http://wp-np3-bd/future/) environment and should get automatically deployed in [dev](http://wp-np3-bd/interpro/) overnight

### CODE REVIEW

**Review by typhainepl — COMMENTED** [review]
Impressive work! Overall everything seems to work fine. The only style issue I spotted is that on the Export menu, the Visual framework-styled buttons go outside the allocated area.
Example: image

Something I noticed is that when deleting one of the sequences in the batch search and downloading through the `Group actions`, the sequence is still there. But I am not sure this is fixable.
 
One thing to work on for the next release will be to have the `gene` available in TSV and Fasta files.

**Comment by gustavo-salazar** [comment]
@typhainepl I think by introducing that bug I should get one of these mugs:
CSS is Awesome

**Review by matthiasblum — APPROVED** [review]
LGTM.

A bunch of minor styling suggestions (non related to the PR):

* Do not uppercase tooltip's titles in [Tooltip/style.css](https://github.com/ProteinsWebTeam/interpro7-client/blob/83273ae9864f3a58f6e683681278649fb0d28e31/src/components/SimpleCommonComponents/Tooltip/style.css#L14).
* Add an `!important` after `text-decoration` rules in [interpro-vf.css](https://github.com/ProteinsWebTeam/interpro7-client/blob/83273ae9864f3a58f6e683681278649fb0d28e31/src/styles/interpro-vf.css#L169C7-L169C7).
* Remove [card-specific link styles](https://github.com/ProteinsWebTeam/interpro7-client/blob/83273ae9864f3a58f6e683681278649fb0d28e31/src/styles/interpro-new.css#L925-L937) as they clash with the new VF styles (e.g. bottom border _and_ underline on hover)
* Add `.protvista-menu {
  margin-top: 0;
}` to [Table/Exporter/style.css](https://github.com/ProteinsWebTeam/interpro7-client/blob/dev/src/components/Table/Exporter/style.css) to align the _Export_ button with other components in the Browse page's table or grid.

**Comment by gustavo-salazar** [comment]
> A bunch of minor styling suggestions 

I just include those changes. However, I only removed the border thing underlining the card titles. I'll review more about it whenever I do the migration to TS for those.

**Comment by typhainepl** [comment]
I just came across an issue with the relationship between entries in the clan Overview, the links between the nodes aren't shown anymore and the nodes are spaced equaly from each other (e.g. cl00011)

**Comment by gustavo-salazar** [comment]
> I just came across an issue with the relationship between entries in the clan Overview, the links between the nodes aren't shown anymore and the nodes are spaced equally from each other (e.g. cl00011)

It's a data problem. But I think that test databases are being refreshed because of the upcoming release.

**Pull request merged**
