### PR TITLE
IDA download JSON and TSV

### PR DESCRIPTION
**Pull request by gustavo-salazar**
This PR adds an Export button to the search by domain architecture, and the DA pages in an InterPro entry.

The `JSON` option creates a single file from the multiple API calls. The `TSV` processes the different attributes of the API response to add them as cells in the TSV.
However, the Domains value for the representative protein is a single string. 
For example the IDA `PF00039:IPR000083-PF00051:IPR000001-PF00089:IPR001254` gets serialized in JSON as:

```json
{
"ida":"PF00039:IPR000083-PF00051:IPR000001-PF00089:IPR001254",
"ida_id":"0dd2a54cf72974f491a9ea729ae694d73c16dc58",
"representative":{
  "accession":"B4DNJ1",
  "length":436,
  "domains":[
    {"accession":"PF00039","name":"fn1","coordinates":[{"fragments":[{"start":41,"end":78}]}]},
    {"accession":"IPR000083","name":"Fibronectin_type1","coordinates":[{"fragments":[{"start":41,"end":78}]}]},
    {"accession":"PF00051","name":"Kringle","coordinates":[{"fragments":[{"start":89,"end":170}]}]},
    {"accession":"IPR000001","name":"Kringle","coordinates":[{"fragments":[{"start":89,"end":170}]}]},
    {"accession":"PF00089","name":"Trypsin","coordinates":[{"fragments":[{"start":185,"end":430}]}]},
    {"accession":"IPR001254","name":"Trypsin_dom","coordinates":[{"fragments":[{"start":185,"end":430}]}]}
  ]
},
"unique_proteins":65
}
```
And in TSV as:
```tsv
IDA ID	IDA Text	Unique Proteins	Representative Accession	Representative Length	Representative Domains
0dd2a54cf72974f491a9ea729ae694d73c16dc58	PF00039:IPR000083-PF00051:IPR000001-PF00089:IPR001254	65	B4DNJ1	436	"PF00039(fn1)[41-78]	IPR000083(Fibronectin_type1)[41-78]	PF00051(Kringle)[89-170]	IPR000001(Kringle)[89-170]	PF00089(Trypsin)[185-430]	IPR001254(Trypsin_dom)[185-430]"
```
----

Additionally, there are a few minor changes in other `.tsx` files where I found leftovers `row` and `column` CSS classes, which shouldn't be there as in theory, typescript files should have also been migrated to the visual framework, and row/column is from foundation.

### CODE REVIEW

**Comment by typhainepl** [comment]
I find it a bit repetitive to have the same coordinates twice (i.e. one for Pfam and one for InterPro), maybe we simplify it.
My suggestion for the JSON format: `{"pfam":{"accession":"PF00039","name":"fn1"},"interpro":{"accession":"IPR000083","name":"Fibronectin_type1"},"coordinates":[{"fragments":[{"start":41,"end":78}]}]}`

My suggestion for the TSV format: `PF00039(fn1):IPR000083(Fibronectin_type1)[41-78]`

**Comment by gustavo-salazar** [comment]
> I find it a bit repetitive to have the same coordinates twice (i.e. one for Pfam and one for InterPro), maybe we simplify it. My suggestion for the JSON format: `{"pfam":{"accession":"PF00039","name":"fn1"},"interpro":{"accession":"IPR000083","name":"Fibronectin_type1"},"coordinates":[{"fragments":[{"start":41,"end":78}]}]}`
> 
> My suggestion for the TSV format: `PF00039(fn1):IPR000083(Fibronectin_type1)[41-78]`

Changes done for the TSV. 
For JSON I wouldn't change as it is the way the API returns this info and I would rather have consistency here. 

Changing it directly in the API implies changes in the search by IDA on the client, plus the unknown of any user already using the current API format. which takes this whole thing out of scope.

**Comment by typhainepl** [comment]
The new TSV format looks good to me, feel free to merge.

**Review by typhainepl — APPROVED** [review]

**Review by matthiasblum — CHANGES_REQUESTED** [review]
Made minor comments regarding the code, but nothing that prevents merging.

However, I have an issue with the TSV format. This is the TSV output for the most common domain that contains `IPR007698` ([link](https://www.ebi.ac.uk/interpro/search/ida/?ida_search=IPR007698)):

|IDA ID|IDA Text|Unique Proteins|Representative Accession|Representative Length|Representative Domains|
|------|--------|---------------|------------------------|---------------------|----------------------|
|a626f37960cbb25225a498edca91012def601c3c|PF05222:IPR007886-PF01262:IPR007698|47145|P17556|372|"PF05222(AlaDh_PNT_N):IPR007886(AlaDH/PNT_N)[4-137]	PF01262(AlaDh_PNT_C):IPR007698(AlaDH/PNT_NAD(H)-bd)[141-354]"|

The representative domains is represented as such:

```
"PF05222(AlaDh_PNT_N):IPR007886(AlaDH/PNT_N)[4-137]\tPF01262(AlaDh_PNT_C):IPR007698(AlaDH/PNT_NAD(H)-bd)[141-354]"
```

Wrapping names with additional parentheses can lead to nesting, given that names themselves can already include parentheses. Curly brackets are not allowed in InterPro short names (and are not used in any Pfam names), so we could use them to enclose names. Additionally, commas are not used in short names as well and could be used to separate individual domains instead of tabs:

```
PF05222{AlaDh_PNT_N}:IPR007886{AlaDH/PNT_N}[4-137],PF01262{AlaDh_PNT_C}:IPR007698{AlaDH/PNT_NAD(H)-bd}[141-354]
```

**Review by matthiasblum — APPROVED** [review]
Looks good to me. Feel free to merge. Thanks!

**Pull request merged**
